src/main/java/br/com/caelum/ingresso/model/DetalhesDoFilme.java
package br.com.caelum.ingresso.model;

import com.fasterxml.jackson.annotation.JsonProperty;

public class DetalhesDoFilme {
    @JsonProperty("Title")
    private String titulo;

    @JsonProperty("Year")
    private Integer ano;

    @JsonProperty("Poster")
    private String imagem;

    @JsonProperty("Director")
    private String diretores;

    @JsonProperty("Writer")
    private String escritores;

    @JsonProperty("Actors")
    private String atores;

    @JsonProperty("Plot")
    private String descricao;

    @JsonProperty("imdbRating")
    private Double avaliacao;

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public Integer getAno() {
        return ano;
    }

    public void setAno(Integer ano) {
        this.ano = ano;
    }

    public String getImagem() {
        return imagem;
    }

    public void setImagem(String imagem) {
        this.imagem = imagem;
    }

    public String getDiretores() {
        return diretores;
    }

    public void setDiretores(String diretores) {
        this.diretores = diretores;
    }

    public String getEscritores() {
        return escritores;
    }

    public void setEscritores(String escritores) {
        this.escritores = escritores;
    }

    public String getAtores() {
        return atores;
    }

    public void setAtores(String atores) {
        this.atores = atores;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Double getAvalicao() {
        return avaliacao;
    }

    public void setAvalicao(Double avaliacao) {
        this.avaliacao = avaliacao;
    }
}

src/main/java/br/com/caelum/ingresso/model/Filme.java
package br.com.caelum.ingresso.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Duration;

/**
 * Created by nando on 03/03/17.
 */
@Entity
public class Filme {

    @Id
    @GeneratedValue
    private Integer id;
    private String nome;
    private Duration duracao;
    private String genero;
    private BigDecimal preco;

    /**
     * @deprecated hibernate only
     */
    public Filme() {

    }
    
    public Filme(String nome, Duration duracao, String genero, BigDecimal preco) {
		this.nome = nome;
		this.duracao = duracao;
		this.genero = genero;
		this.preco = preco;
	}

    public BigDecimal getPreco() {
        return preco;
    }

    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Duration getDuracao() {
        return duracao;
    }

    public void setDuracao(long duracao) {
        this.duracao = Duration.ofMinutes(duracao);
    }

    public String getGenero() {
        return genero;
    }

    public void setGenero(String genero) {
        this.genero = genero;
    }
}

src/main/java/br/com/caelum/ingresso/controller/FilmeController.java
package br.com.caelum.ingresso.controller;

import br.com.caelum.ingresso.dao.FilmeDao;
import br.com.caelum.ingresso.dao.SessaoDao;
import br.com.caelum.ingresso.model.DetalhesDoFilme;
import br.com.caelum.ingresso.model.Filme;
import br.com.caelum.ingresso.model.Sessao;
import br.com.caelum.ingresso.rest.ImdbClient;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;

import javax.validation.Valid;
import java.util.List;
import java.util.Optional;

/**
 * Created by nando on 03/03/17.
 */
@Controller
public class FilmeController {


    @Autowired
    private FilmeDao filmeDao;

    @Autowired
    private SessaoDao sessaoDao;

    @Autowired
    private ImdbClient imdbClient;

    @GetMapping("/filme/{id}/detalhe")
    public ModelAndView detalhes(@PathVariable("id") Integer id) {
        ModelAndView modelAndView = new ModelAndView("/filme/detalhe");
        Filme filme = filmeDao.findOne(id);
        List<Sessao> sessoes = sessaoDao.buscaSessoesDoFilme(filme);
        Optional<DetalhesDoFilme> detalhesDoFilme = imdbClient.request(filme, DetalhesDoFilme.class);
        modelAndView.addObject("filme", filme);
        modelAndView.addObject("detalhes", detalhesDoFilme.orElse(new DetalhesDoFilme()));
        modelAndView.addObject("sessoes", sessoes);
        return modelAndView;
    }


    @GetMapping("/filme/em-cartaz")
    public ModelAndView emCartaz() {
        ModelAndView modelAndView = new ModelAndView("/filme/em-cartaz");
        modelAndView.addObject("filmes", filmeDao.findAll());
        return modelAndView;
    }

    @GetMapping({"/admin/filme", "/admin/filme/{id}"})
    public ModelAndView form(@PathVariable("id") Optional<Integer> id, Filme filme){

        ModelAndView modelAndView = new ModelAndView("/filme/filme");

        if (id.isPresent()){
            filme = filmeDao.findOne(id.get());
        }

        modelAndView.addObject("filme", filme);

        return modelAndView;
    }


    @PostMapping("/admin/filme")
    @Transactional
    public ModelAndView salva(@Valid Filme filme, BindingResult result){

        if (result.hasErrors()) {
            return form(Optional.ofNullable(filme.getId()), filme);
        }

        filmeDao.save(filme);

        ModelAndView view = new ModelAndView("redirect:/admin/filmes");

        return view;
    }


    @GetMapping(value="/admin/filmes")
    public ModelAndView lista(){

        ModelAndView modelAndView = new ModelAndView("filme/lista");

        modelAndView.addObject("filmes", filmeDao.findAll());

        return modelAndView;
    }

    @DeleteMapping("/admin/filme/{id}")
    @ResponseBody
    @Transactional
    public void delete(@PathVariable("id") Integer id){
        filmeDao.delete(id);
    }

}

src/main/webapp/WEB-INF/views/filme/detalhe.jsp
<%--
  Created by IntelliJ IDEA.
  User: nando
  Date: 20/01/17
  Time: 12:51
  To change this template use File | Settings | File Templates.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib tagdir="/WEB-INF/tags/" prefix="ingresso" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>

<ingresso:template>
    <jsp:body>
		<div class=" col-md-6 col-md-offset-3">
	        <h1>${detalhes.titulo}</h1>
	        <image src="${detalhes.imagem}" />
	
	        <div>
	            <label for="ano">Ano</label>
	            <span id="ano">${detalhes.ano}</span>
	        </div>
	
	        <div>
	            <label for="diretores">Diretores</label>
	            <span id="diretores">${detalhes.diretores}</span>
	        </div>
	
	        <div>
	            <label for="escritores">Escritores</label>
	            <span id="escritores">${detalhes.escritores}</span>
	        </div>
	
	        <div>
	            <label for="atores">Atores</label>
	            <span id="atores">${detalhes.atores}</span>
	        </div>
	
	        <div>
	            <label for="descricao">Descrição</label>
	            <span id="descricao">${detalhes.descricao}</span>
	        </div>
	
	        <div>
	            <label for="avaliacao">Avaliação</label>
	            <span id="avaliacao">${detalhes.avalicao}</span>
	        </div>

			<%-- <sec:authorize access="hasRole('COMPRADOR')"> --%>
				<table class="table table-hover">
					<thead>
						<th>Sala</th>
						<th>Horario</th>
						<th>Ações</th>
					</thead>
					<tbody>
						<c:forEach items="${sessoes}" var="sessao">
							<tr>
								<td>${sessao.sala.nome}</td>
								<td>${sessao.horario}</td>
								<td>
									<a href="/sessao/${sessao.id}/lugares" class="btn">
										Comprar
										<span class="glyphicon glyphicon-blackboard" aria-hidden="true"></span>
									</a>
								</td>
							</tr>
						</c:forEach>
					</tbody>
				</table>
			<%-- </sec:authorize> --%>
		</div>
    </jsp:body>
</ingresso:template>

src/main/webapp/WEB-INF/views/filme/em-cartaz.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib tagdir="/WEB-INF/tags/" prefix="ingresso" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<ingresso:template>
    <jsp:body>
        <div class=" col-md-6 col-md-offset-3">
            <c:forEach var="filme" items="${filmes}">

                <div class="col-md-4 ">
                    <a href="/filme/${filme.id}/detalhe">
                        <div class="panel panel-default panelSize">
                            <div class="panel-heading text-center"><strong>${filme.nome}</strong></div>
                            <div class="panel-body">
                                <div>
                                    <strong>Genero:</strong> ${filme.genero}
                                </div>
                                <div>
                                    <strong>Duração:</strong> ${filme.duracao.toMinutes()} minutos
                                </div>
                            </div>
                        </div>
                    </a>
                </div>

            </c:forEach>
        </div>

        <style>
            a:hover {
                text-decoration: none;
            }

            .panel {
                transition: transform 0.7s;
            }

            .panel:hover {
                transform: translateY(-0.5em);
            }

            .panelSize {
                min-height: 10.5em;
                min-width: 13em;
            }
        </style>
    </jsp:body>
</ingresso:template>

src/main/webapp/WEB-INF/views/filme/filme.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib tagdir="/WEB-INF/tags/" prefix="ingresso" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<ingresso:template>
    <jsp:body>
		<div class=" col-md-6 col-md-offset-3">
        <c:set var="bindingResult" value="${requestScope['org.springframework.validation.BindingResult.filme']}"/>

        <form action='/admin/filme' method="post">
            <input type="hidden" name="id" value="${filme.id}">

            <div class="form-group">
                <label for="nome">Nome:</label>
                <input id="nome" type="text" name="nome" class="form-control" value="${filme.nome}">
                <c:forEach items="${bindingResult.getFieldErrors('nome')}" var="error">
                    <span class="text-danger">${error.defaultMessage}</span>
                </c:forEach>
            </div>

            <div class="form-group">
                <label for="genero">Genero:</label>
                <input id="genero" type="text" name="genero" class="form-control" value="${filme.genero}">
                <c:forEach items="${bindingResult.getFieldErrors('genero')}" var="error">
                    <span class="text-danger">${error.defaultMessage}</span>
                </c:forEach>
            </div>

            <div class="form-group">
                <label for="duracao">Duracao:</label>
                <input id="duracao" type="text" name="duracao" class="form-control"
                       value="${filme.duracao.toMinutes()}">
                <c:forEach items="${bindingResult.getFieldErrors('duracao')}" var="error">
                    <span class="text-danger">${error.defaultMessage}</span>
                </c:forEach>
            </div>
		

 			<div class="form-group">
 				<label for="preco">Preço:</label>
                <input id="preco" type="text" name="preco" class="form-control" value="${filme.preco}">
                <c:forEach items="${bindingResult.getFieldErrors('preco')}" var="error">
                <span class="text-danger">${error.defaultMessage}</span>
                </c:forEach>
 			</div>

            <button type="submit" class="btn btn-primary">Gravar</button>
        </form>
        </div>
    </jsp:body>
</ingresso:template>

src/main/webapp/WEB-INF/views/filme/lista.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib tagdir="/WEB-INF/tags/" prefix="ingresso"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>


<ingresso:template>
	<jsp:body>
		<div class=" col-md-6 col-md-offset-3">
		<table class="table table-hover ">
			<thead>
				<tr>
					<th>Nome</th>
					<th>Duração</th>
					<th>Preço</th>
					<th colspan="2" class="text-center">Ações</th>
				</tr>
			</thead>
			<tbody>
				<c:forEach var="filme" items="${filmes}">
					<tr>
						<td>${filme.nome}</td>
						<td>${filme.duracao.toMinutes()}</td>
						<td>${filme.preco}</td>
						<td>
							<a onclick="excluir(${filme.id})" class="btn btn-danger">Excluir</a>
						</td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
		<div class="col-md-6 col-md-offset-3">
			<a href="/admin/filme" class="btn btn-block btn-info">Novo</a>
		</div>
		</div>
		<script>
			function excluir(id) {
				var url = window.location.href;
				$.ajax({
					url:"/admin/filme/" + id,
					type: 'DELETE',
					success: function (result) {
						console.log(result);

						window.location.href = url;
					}
				});
			}
		</script>
	</jsp:body>
</ingresso:template>